//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company_Store_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Export_product
    {
        public int Perm_id { get; set; }
        public int product_id { get; set; }
        public int quantity { get; set; }
    
        public virtual Export_perm Export_perm { get; set; }
        public virtual Product Product { get; set; }
    }
}
