//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company_Store_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transfer_Product
    {
        public int Transfer_id { get; set; }
        public Nullable<int> From_store_id { get; set; }
        public Nullable<int> To_store_id { get; set; }
        public Nullable<int> Supplier_id { get; set; }
        public Nullable<int> Product_id { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string unit { get; set; }
        public Nullable<System.DateTime> Production_date { get; set; }
        public Nullable<System.DateTime> Expire_date { get; set; }
        public Nullable<System.DateTime> Transfer_date { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Store Store { get; set; }
        public virtual Store Store1 { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
